name: Build/test
on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "master"
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install nan tree-sitter-cli
      - run: export PATH=$PATH:./node_modules/.bin
      - run: npx tree-sitter generate
      - run: npx tree-sitter test
